### ISSUE TITLE
restart / install on running raspiblitz: lightning is always offline

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#120]
wen restarting the installed blitzapi service with 

`sudo systemctl restart blitzapi.service`

or when installing over the install script, the `system_startup_message` always displays lightning as offline:

`{"bitcoin": "done", "bitcoin_msg": "", "lightning": "offline", "lightning_msg": ""}`

Reboot of RaspiBlitz fixes this.

**Comment by rootzoll** [comment]
For me its the otherway round (with a patched RC2) .. when I boot up fresh a CLN node - I get:
`{"bitcoin": "offline", "bitcoin_msg": "", "lightning": "disabled", "lightning_msg": ""}`

When I restart the ´blitzapi` service tnru the terminal & reload the WebUI - it catches up normal with:
`{"bitcoin": "done", "bitcoin_msg": "", "lightning": "done", "lightning_msg": ""}`

**Comment by rootzoll** [comment]
OK - the ball could be in my side here. After a reboot the `.env` is not correct. Will check the pre-config script.

**Comment by fusion44** [comment]
Can I close this?
