### ISSUE TITLE
open-channel does not work

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#122]
When trying to open the channel with the following payload, I get an error.

Should be 120k sat

```
{
  "local_funding_amount": 120000,
  "node_URI": "024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365@84.16.229.1:9735",
  "target_confs": 20
}
```

The error:

```
{
  "detail": [
    { "loc": ["query", "local_funding_amount"], "msg": "field required", "type": "value_error.missing" },
    { "loc": ["query", "node_URI"], "msg": "field required", "type": "value_error.missing" }
  ]
}
```

**Comment by openoms** [comment]
Does not work with CLN either

**Comment by cstenglein** [comment]
Was my bad, fixed by https://github.com/fusion44/blitz_api/issues/122

**Comment by openoms** [comment]
Needs to have a symlink for CLN:
```
  sudo ln -s /mnt/hdd/app-data/.lightning /home/blitzapi/
```
adding it to the install script.

**Comment by openoms** [comment]
Opened a channel from the UI with CLN, but it opened while an error was displayed likely related to: https://github.com/fusion44/blitz_api/issues/126#issuecomment-1171963281
