### ISSUE TITLE
hardware_info message does not get sent regularly

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#124]
![image](https://user-images.githubusercontent.com/9399034/174486238-acf09aea-23aa-49cd-924c-42f236a3ab94.png)

Just seems to get sent once, then never again

**Comment by cstenglein** [comment]
Could be related to https://github.com/rootzoll/raspiblitz/issues/3175

**Comment by fusion44** [comment]
Looks like a number conversion error.

**Comment by openoms** [comment]
#3175 was specific to ZFS (the byte calculation was off as the size was showing dinamically eg 800G used vs 1.2T)

**Comment by cstenglein** [comment]
Can be closed AFAIK with the refactor @fusion44

**Comment by fusion44** [comment]
If not, open a new issue please.
