### ISSUE TITLE
num_confs of a transactions are negative

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#137]
![image](https://user-images.githubusercontent.com/9399034/181692726-0114499c-790b-4594-8d35-1eb8f3eb6123.png)

**Comment by cstenglein** [comment]
After the tx succeeded, it showed the correct number of confs.

**Comment by fusion44** [comment]
Can't reproduce. Is this LND?

**Comment by cstenglein** [comment]
Yes, LND

**Comment by fusion44** [comment]
That's odd since I literally just forward 1:1 what I get from LND. I've added a log function to LND too.

**Comment by fusion44** [comment]
@cstenglein Do you still experience this?

**Comment by cstenglein** [comment]
Currently not => can be closed for now
