### ISSUE TITLE
can't send all funds out on-chain

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#139]
If I have 210k sats & want to send 210k sats (i.e. all funds) to another on-chain address, this doesn't work

I get a 500 response from `lightning/send-coins`

**Comment by fusion44** [comment]
Please ssh into the Blitz and observe the logs: `sudo journalctl -fu blitzapi`
What is the error?

**Comment by fusion44** [comment]
I was just thinking about this. What is probably happening here is that if you try to send out all funds, nothing is left to cover the network fees. Not sure how to handle actually this server side. Maybe its best to add an extra endpoint `sweep-funds` for this and let the node implementation handle the details. Nonetheless this shouldn't return a 500.

**Comment by cstenglein** [comment]
https://api.lightning.community/#sendcoins use `send_all`

**Comment by fusion44** [comment]
@cstenglein Please test this. Seems to work for me. Especially, try to break the API :crossed_swords: 

From the docs:
![image](https://user-images.githubusercontent.com/503952/204349763-23073884-0bd2-4551-a724-df69eaf7e2cc.png)

**Comment by cstenglein** [comment]
Your commit is in the `refactor_system` branch which Is blocked by https://github.com/fusion44/blitz_api/pull/149#issuecomment-1328610770 so I can't test it.

**Comment by fusion44** [comment]
This should work now.
