### ISSUE TITLE
use cookie for sse authentication

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#144]
As a developer I would like to use the native eventsource, not a external package for the SSE authentication.

Thus the sse authentication would require a cookie.

**Comment by cstenglein** [comment]
The main reason for this is that the polyfill modifies the eventsource so the events don't show up in the network tab (https://github.com/Yaffle/EventSource/issues/208) in addition to some weird behaviour they added recently (https://github.com/Yaffle/EventSource/issues/205 & https://github.com/Yaffle/EventSource/issues/205)

So I would really like to get this dependency out as fast as possible.

**Comment by fusion44** [comment]
For future reference:

https://github.com/alex-oleshkevich/starsessions <== Fav
https://github.com/rafsaf/minimal-fastapi-postgres-template
https://github.com/Tert0/fastapi-framework
