### ISSUE TITLE
API doesn't send "installed_app_status" 

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#157]
In the current version of the API, it doesn't send the "installed_app_status" message on a new connection.

Messages:

![image](https://user-images.githubusercontent.com/9399034/196371257-b0a0a5c8-f471-4474-a08b-0bf2b155ba19.png)

Even after restart they are missing:

![image](https://user-images.githubusercontent.com/9399034/196373055-89a2825e-5b74-4d8d-b644-de876fceb7c5.png)

**Comment by fusion44** [comment]
Yes, see https://github.com/fusion44/blitz_api/commit/4408a6a58cb5e5ac94f8cf41e109bb33df58c39c

Will be fixed once #149 is merged. Until then this must stay disabled, otherwise it makes local development a hassle as it'll constantly ask for root password.

**Comment by fusion44** [comment]
s a quick fix you can always go to https://github.com/cstenglein/blitz_api/blob/beba4332e7f6da1b96af74d8ddc0cd863896ee6c/app/repositories/utils.py#L37 and uncomment the get_app_status calls.
