### ISSUE TITLE
Add endpoint to decode invoice

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#16]
As a user I would like to see the amount etc. of a LN invoice before paying it.

Thus I would like to have an REST endpoint (no SSE event needed) to decode the LN invoice and show me the relevant information.

**Comment by fusion44** [comment]
Its in. I've decided to use the LND terminology of decoding a "payment request".

![image](https://user-images.githubusercontent.com/503952/134025324-b3fcc534-c224-4894-be46-8783221ad5e4.png)
