### ISSUE TITLE
HTTP error 500 when querying /system/get-debug-logs-raw

### ISSUE THREAD

**Issue by fusion44** [fusion44/blitz_api#160]
**Describe the bug**
Error when querying raw debug log endpoint

Error message from RaspiBlitz:
```json
{
  "detail": "\n    f\"['bash /home/admin/config.scripts/blitz.debug.sh' exited with 0]\"\n\n    [stderr]\nTERM environment variable not set.\n\n            "
}
```

native_python:
```python
    except NotImplementedError as r:
        raise HTTPException(status.HTTP_501_NOT_IMPLEMENTED, detail=r.args[0])
```
NotImplementedError doesn't have an args array

**Expected behavior**
No error message

**Desktop (please complete the following information):**
 - LN implementation: -
 - Platform: all but for different reasons

**Comment by cstenglein** [comment]
Fixed
