### ISSUE TITLE
Build API for fetching Raspiblitz log

### ISSUE THREAD

**Issue by fusion44** [fusion44/blitz_api#18]
https://github.com/cstenglein/raspiblitz-web/issues/49

**Comment by fusion44** [comment]
Endpoint is in, but not tested yet on a real Raspiblitz. Access via `http://127.0.0.1:8000/latest/system/get_debug_logs_raw`. Make sure to pass a valid JWT token.

![image](https://user-images.githubusercontent.com/503952/133981291-eda8a51e-5140-4365-849b-78d5bd85cff8.png)

**Comment by nyxnor** [comment]
Sorry for the confusion, the next release will change the file home.admin/XXdebugLogs.sh to https://github.com/rootzoll/raspiblitz/blob/dev/home.admin/config.scripts/blitz.debug.sh
