### ISSUE TITLE
list-all-tx fails on fresh CLN node (v1.9.0rc4)

### ISSUE THREAD

**Issue by rootzoll** [fusion44/blitz_api#203]
**Describe the bug**

Dasboard is loading forever on first entering after setup. Call to `lightning/list-all-tx?reversed=true` fails.

![Bildschirmfoto 2023-05-08 um 18 38 09](https://user-images.githubusercontent.com/2472225/236921055-f5cdccee-b077-4f30-912a-1bd3e24d9a08.png)

![Bildschirmfoto 2023-05-08 um 18 54 28](https://user-images.githubusercontent.com/2472225/236921069-1c4ba4c2-3ad1-4a0c-b824-cab6e9be62cf.png)

**To Reproduce**

Install a fresh CLN node based on v1.9.0rc4 and login into WebUI.

**Comment by fusion44** [comment]
@rootzoll I guess this can be closed now?
