### ISSUE TITLE
Wrong balance for LN channel with "wallet_balance" message / lightning/get-balance endpoint

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#27]
I got the following channel:

![image](https://user-images.githubusercontent.com/9399034/137174659-4743152a-8dc2-4a33-82ff-bb50718f4125.png)

The endpoint & the wallet_balance message gives me the following result:

```json
{
  "onchain_confirmed_balance": 742363,
  "onchain_total_balance": 742363,
  "onchain_unconfirmed_balance": 0,
  "channel_local_balance": 140950000,
  "channel_remote_balance": 100000000,
  "channel_unsettled_local_balance": 0,
  "channel_unsettled_remote_balance": 0,
  "channel_pending_open_local_balance": 0,
  "channel_pending_open_remote_balance": 0
}
```

140950000 => 140_950_000 are three zeros too much. for channel_local_balance & channel_remote_balance

The onchain_confirmed_balance is correct though:

![image](https://user-images.githubusercontent.com/9399034/137175047-0a164ebe-8748-433d-a353-d4a6a5969a38.png)

**Comment by fusion44** [comment]
In lightning we deal with millisats ;)

Take a look at the docs:
https://github.com/fusion44/blitz_api/blob/6ad707e3eac95eb6ca0b18194dcab8077ff89392/app/models/lightning.py#L941

All `channel_*` results are in msat. I propbably should rename those from `channel_local_balance` to `channel_local_balance_msat`?

**Comment by cstenglein** [comment]
I think it should be enough to mention it in the swagger documentation, it currently only says:

`A JSON String with on chain wallet balances.`

**Comment by fusion44** [comment]
In the schema you can see which values are in sat and which in msat. 
But I'll make it more clear from the general description anyway.

**Comment by cstenglein** [comment]
Ah you are right! - my bad :/

> But I'll make it more clear from the general description anyway.

Should i leave it open then?
