### ISSUE TITLE
Use "type" of MessageEvent for SSE Events instead of "lastEventId"

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#28]
As discussed in Twitter DMs:

`blitz_api` sends the messages with an `id` which is then used in a `MessageEvent` as `lastEventId`(MDN documentation [here](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/MessageEvent).

In `raspiblitz-web` I'm differentiating between the `type` of the `MessageEvent`though, which not lets the web UI receive the messages, but it can't process them.

Changing the  lines [here](https://github.com/fusion44/blitz_api/blob/main/app/main.py#L112-L116) works, but needs to be done for the "regular" events as well.

**Comment by fusion44** [comment]
Fixed with #38
