### ISSUE TITLE
Add endpoint to give me a list of mock transactions

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#37]
Since #30 will take some more time, give me a list of mock transactions please :)

Example: https://github.com/cstenglein/raspiblitz-web/blob/master/backend-mock/transactions.js

Don't know if these fields are fine, will adapt to your solution :+1:

**Comment by fusion44** [comment]
Working on actually implementing #30 soon. Groundwork is done. Should be ready in a few days.
