### ISSUE TITLE
Make shell_script_path more configurable

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#39]
Currently it's more like hidden knowledge that you need to specify a path with shell_script_path where a config.scripts folder with a file called blitz.debug.sh in it.

See also my note here: https://github.com/cstenglein/raspiblitz-web#blitz-api

=> Make shell_script_path more configurable (maybe with an extra file property?)

**Comment by fusion44** [comment]
Not sure what you mean by _extra file property_?

I'll change the README to make it more clear that the script path must be specified in the .env file.

**Comment by cstenglein** [comment]
Closed for now.

I think the best way would be to have a working guide in the README to have a working local setup. Currently with the recent additions, that's not (easily) possible anymore.
