### ISSUE TITLE
make install on OSX fails

### ISSUE THREAD

**Issue by geco91** [fusion44/blitz_api#40]
Not able to install the requirements on a OSX system:

```
> blitz_api % make install
python -m pip install -r requirements.txt
Ignoring cffi: markers 'implementation_name == "pypy" and python_version >= "3.6"' don't match your environment
Ignoring colorama: markers 'python_version >= "3.6" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.6" and python_full_version >= "3.5.0"' don't match your environment
Collecting fastapi-versioning@ git+https://github.com/fusion44/fastapi-versioning@master
ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
    fastapi-versioning@ git+https://github.com/fusion44/fastapi-versioning@master from git+https://github.com/fusion44/fastapi-versioning@master (from -r requirements.txt (line 151))
make: *** [install] Error 1
```

**Comment by geco91** [comment]
Is it because i have Python 3.9.6 running?

**Comment by fusion44** [comment]
Sorry, no this is my fault. I've forked fastapi-versioning and fetch the forked version. At the moment the only option is to install via poetry as there is not a way to tell pip to ignore the hashes.

You can find instructions about poetry in the [README](https://github.com/fusion44/blitz_api#development) file.

**Comment by cstenglein** [comment]
This also makes the build fail on Raspiblitz @fusion44 

The solution is to comment out the fastapi-versioning and installing the normal version by hand.

**Comment by fusion44** [comment]
Yes, I'm working on it. Will include the package directly.
