### ISSUE TITLE
Add endpoint to estimate fees

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#44]
As a user I would like to know how much I need to pay for my on-chain transactions to get into the next X blocks to not overpay .

**Comment by cstenglein** [comment]
@rootzoll important issue

**Comment by fusion44** [comment]
LND: https://api.lightning.community/#estimatefee
c-lightning: https://lightning.readthedocs.io/lightning-feerates.7.html

**Comment by fusion44** [comment]
To avoid having to juggle with implementation differences the endpoint is implemented by querying Bitcoin Core directly, thus the Bitcoin Core documentation applies.

The endpoint returns the fees in sats as msat are irrelevant when sending on-chain.

Bitcoin Core documentation: https://developer.bitcoin.org/reference/rpc/estimatesmartfee.html

![image](https://user-images.githubusercontent.com/503952/144763039-cfe71b32-add7-4c11-b712-cf5d8612510c.png)
