### ISSUE TITLE
Finish implementation of  /system/get-system-info

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#47]
@rootzoll important issue

**Comment by fusion44** [comment]
I think what remains open here, is to fetch the actual values from the system instead of returning fake values.

**Comment by cstenglein** [comment]
Yes & in addition there should be an additional property which contains the node id so people can connect to it.

This is relevant for cstenglein/raspiblitz-web#120

**Comment by fusion44** [comment]
You can get the idendity pubkey via `/lightning/get-info`, but I'll add it to system info too.

**Comment by cstenglein** [comment]
No worries, don't need it in two places :)

**Comment by fusion44** [comment]
@cstenglein It's implemented except the health message related stuff. And there is a tiny breaking change:

### Response json:
```json
{
  "alias": "testiblitz2",
  "color": "#3399ff",
  "platform": "raspiblitz", // new
  "platform_version": "1.7.2rc1", // renamed from: version
  "api_version": "v0.5.0beta", // new
  "health": "attention_required",
  "health_messages": [
    {
      "id": 25,
      "level": "warning",
      "message": "HDD 85% full"
    }
  ],
  "tor_web_ui": "ar76cct7atr6heahj5qfsppcpc5a6sjl2sg76jzvfld7lth3i4oqtayd.onion",
  "tor_api": "ar76cct7atr6heahj5qfsppcpc5a6sjl2sg76jzvfld7lth3i4oqtayd.onion/api",
  "lan_web_ui": "http://192.168.1.49/",
  "lan_api": "http://192.168.1.49/api",
  "ssh_address": "admin@192.168.1.49",
  "chain": "testnet"
}
```

There are new options in the .env file if you run the instance not on a Blitz but with `platform=native-python`.

**Comment by cstenglein** [comment]
I implemented => Closed
