### ISSUE TITLE
Token expiry is in milliseconds, not seconds

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#53]
https://github.com/fusion44/blitz_api/blob/main/.env_sample#L3 says expiry time in seconds.

Running a few tests, I conclude these are in fact milliseconds :)

**Comment by fusion44** [comment]
Yes, the actual expiry time with the JWT is delivered in milliseconds. I agree this is confusing.

I think it'd be more user friendly and clear to set expiry time in the .env this way:
```sh
jwt_expiry_time="500000ms"
jwt_expiry_time="300s"
jwt_expiry_time="3d"
jwt_expiry_time="3m"
jwt_expiry_time="1y"
```

But the JWT expiry time will always remain in milliseconds.

**Comment by cstenglein** [comment]
What I meant is that the `.env` specifies 300seconds by default as expiry time, but the token that was created only has 300**milliseconds** expiry time.

This makes it that with the default configuration, the webui permanenty logs out after refresh, since the token is not valid anymore.

**Comment by cstenglein** [comment]
To reproduce:

- have 300 in `.env` (default value)
- create token with `system/login` in swagger
- go to [jwt.io](https://jwt.io) and get expiry time
- go to [https://www.epochconverter.com/](https://www.epochconverter.com/) and convert timestamp to local time 
  - will then show `a few seconds ago` in relative time instead of 10min in the future.

**Comment by cstenglein** [comment]
@rootzoll check if expiry is checked correctly

+ https://github.com/fusion44/blitz_api/blob/main/.env_sample => change "seconds" to "milliseconds"
