### ISSUE TITLE
Add option to send amount with send-payment

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#63]
If I want to pay a 0 amount invoice, then I get the following error 

Example invoice: 

`lnbcrt1ps6hyqqpp5shls2yek2mxvm9seek8yl4w2c0jts0j63u7sanl6geqgf72ndhvsdq8w3jhxaqcqzpgxqrrsssp5xpvyhfe0euruhvj99cseczh5jfh75nxeu4vmfdexxfa4068jtp7q9qyyssqpmjdulnu6nh8nj2njhqkdhurf36042k4knx75yu4nm75m4g770pq6ahv66l8tp7weed6vte3k9axjqn2s4yceppthtr79xtgg3wdgfsqn2lz6k`

Error:

`TypeError: _check_if_locked() missing 1 required positional argument: 'error'`

As a user I want to pay 0 sat invoices as well. The functionality is implemented in cstenglein/raspiblitz-web#159 already but there is a query param missing to tell blitz_api the amount.

**Comment by cstenglein** [comment]
Awesome, thx! :)

**Comment by fusion44** [comment]
Gerne :D

Christoph Stenglein ***@***.***> schrieb am So., 9. Jan.
2022, 21:38:
