### ISSUE TITLE
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==

### ISSUE THREAD

**Issue by escapedcat** [fusion44/blitz_api#65]
Last time I started it up it worked, now I get:

```sh
python3 -m pip install -r requirements.txt

...

ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=3.6.5 from https://files.pythonhosted.org/packages/05/e4/baf0031e39cf545f0c9edd5b1a2ea12609b7fcba2d58e118b11753d68cf0/typing_extensions-4.0.1-py3-none-any.whl#sha256=7f001e5ac290a0c0401508864c7ec868be4e701886d5b573a9528ed3973d9d3b (from async-timeout==4.0.1->-r requirements.txt (line 86))
```

Not sure what I missed. Could also be my current python setup which is a bit of a mess I think.  
Tried to use [pyenv](https://medium.com/@sri_40116/starting-with-pyenv-poetry-for-python-development-9180720bbed5).

**Comment by fusion44** [comment]
Are you sure you use the newest version?

From requirements.txt: `typing-extensions==4.0.0`

Seems like your error references `typing-extensions>=3.6.5`

**Comment by escapedcat** [comment]
I guess I f***ed up my python setup. Would be great to just start a docker container :P

**Comment by fusion44** [comment]
Working on the docker thing already 😁
