### ISSUE TITLE
"initialsync" is always set to "running", even after inital sync is done

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#76]
On my testnode, when i call `/setup/status` I get the following response:

```json
{
  "setupPhase": "done",
  "state": "ready",
  "message": "Node Running",
  "initialsync": "running"
}
```

`initalsync` is set to "running" even though the setup and the initalsync is done. This then leads to a setupscreen and thus the user can't ever login:
https://github.com/cstenglein/raspiblitz-web/blob/setupui/src/App.tsx#L37-L39=

CC @rootzoll

**Comment by rootzoll** [comment]
should be fixed in installapps branch of API
