### ISSUE TITLE
add identity_uri to /lightning/get-info

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#88]
as a user I would like others to connect to my node to open channels to me.

in`system-info` there is just the alias, not the nodeId

CC @rootzoll

**Comment by fusion44** [comment]
Please name it `identity_pubkey` to keep the naming consistent with LnInfo.

Was discussed previously in #47

**Comment by rootzoll** [comment]
@fusion44 its not just the pubkey ... basically its the advertised node URI: pubkey@lndtor:port should it still be called `identity_pubkey`?

**Comment by rootzoll** [comment]
Should I call it `identity_uri`?

**Comment by fusion44** [comment]
Hmm no, then not. I'd argue that it better fits into `lightning/get-info` as it isn't necessarily a system thing. Especially since RaspiBlitz can run without Lightning enabled.

**Comment by rootzoll** [comment]
OK https://github.com/fusion44/blitz_api/pull/89 waiting for merge

**Comment by rootzoll** [comment]
@cstenglein PR https://github.com/fusion44/blitz_api/pull/89 is merged
