### ISSUE TITLE
LnInfoLite is missing "identity_pubkey"

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#94]
Currently, the `identity_pubkey` is only available in the `lightning/get-info` & most likely the respective message.

As a user, I would like to have that field in `lightning/get-info-lite` as well (since I only use the lite info for the dashboard).

**Comment by cstenglein** [comment]
@rootzoll important otherwise the connectioncard keeps spinning

**Comment by rootzoll** [comment]
Added info to endpoint - was able to test PR for `lnd` - but `cl` had problems (might be related to other issue) so was not able to check if it also works for `cl`
